apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ahfn65n1x-nodejs 
  janus-idp.io/tekton: ahfn65n1x-nodejs
  backstage.io/kubernetes-id: ahfn65n1x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ahfn65n1x-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  